# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 03:07
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=50)),
                ('ra', models.IntegerField(unique=True)),
                ('perfil', models.CharField(default='C', max_length=1)),
                ('ativo', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=80)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', app.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArquivosQuestao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.IntegerField(verbose_name='NumeroQuestao')),
                ('arquivo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivosResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('sigla', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('carga_horaria', models.IntegerField(verbose_name='Carga_Horaria')),
                ('teoria', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ementa', models.TextField(blank=True)),
                ('competencias', models.TextField(blank=True)),
                ('habilidades', models.TextField(blank=True)),
                ('conteudo', models.TextField(blank=True)),
                ('bibliografia_basica', models.TextField(blank=True)),
                ('bibliografia_complementar', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('semestre', models.CharField(max_length=1)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('semestre', models.CharField(max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('gradecurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GradeCurricular')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disciplina')),
                ('gradecurricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GradeCurricular')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('data_limite_entrega', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avaliacao', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_de_envio', models.DateField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Questao')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=15)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disciplina')),
                ('disciplinaOfertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DisciplinaOfertada')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Curso')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apelido', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.usuario',),
        ),
        migrations.AddField(
            model_name='questao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Turma'),
        ),
        migrations.AddField(
            model_name='cursoturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Turma'),
        ),
        migrations.AddField(
            model_name='arquivosresposta',
            name='resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Resposta'),
        ),
        migrations.AddField(
            model_name='arquivosquestao',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Questao'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Professor'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Aluno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Aluno'),
        ),
    ]
